# Generated by Django 5.0.3 on 2024-04-06 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usergroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
