# Generated by Django 5.0.3 on 2024-04-04 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=16)),
                ('price', models.FloatField()),
                ('manufacturing_date', models.DateField()),
                ('expiry_date', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
